# Generated by Django 5.0.6 on 2024-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={"verbose_name": "لایک", "verbose_name_plural": "لایک ها"},
        ),
        migrations.AlterModelOptions(
            name="saved",
            options={"verbose_name": "سیو", "verbose_name_plural": "سیو ها"},
        ),
        migrations.AddField(
            model_name="comment",
            name="is_ok",
            field=models.BooleanField(default=False, verbose_name="اجازه انتشار"),
        ),
    ]
