# Generated by Django 5.0.6 on 2024-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_post_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="توضیحات"
            ),
        ),
    ]
